<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto

namespace Cart;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>cart.Cart</code>
 */
class Cart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 rec_id = 1;</code>
     */
    private $rec_id = 0;
    /**
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     */
    private $user_id = 0;
    /**
     * Generated from protobuf field <code>string session_id = 3;</code>
     */
    private $session_id = '';
    /**
     * Generated from protobuf field <code>int32 goods_id = 4;</code>
     */
    private $goods_id = 0;
    /**
     * Generated from protobuf field <code>string goods_sn = 5;</code>
     */
    private $goods_sn = '';
    /**
     * Generated from protobuf field <code>string goods_name = 6;</code>
     */
    private $goods_name = '';
    /**
     * Generated from protobuf field <code>double market_price = 7;</code>
     */
    private $market_price = 0.0;
    /**
     * Generated from protobuf field <code>double goods_price = 8;</code>
     */
    private $goods_price = 0.0;
    /**
     * Generated from protobuf field <code>int32 goods_number = 9;</code>
     */
    private $goods_number = 0;
    /**
     * Generated from protobuf field <code>string goods_attr = 10;</code>
     */
    private $goods_attr = '';
    /**
     * Generated from protobuf field <code>string custom_size = 11;</code>
     */
    private $custom_size = '';
    /**
     * Generated from protobuf field <code>int32 can_handsel = 12;</code>
     */
    private $can_handsel = 0;
    /**
     * Generated from protobuf field <code>string goods_attr_id = 13;</code>
     */
    private $goods_attr_id = '';
    /**
     * Generated from protobuf field <code>int32 goods_off = 14;</code>
     */
    private $goods_off = 0;
    /**
     * Generated from protobuf field <code>int32 lmt_num = 15;</code>
     */
    private $lmt_num = 0;
    /**
     * Generated from protobuf field <code>int32 addtime = 16;</code>
     */
    private $addtime = 0;
    /**
     * Generated from protobuf field <code>string attr_goods_sn = 17;</code>
     */
    private $attr_goods_sn = '';
    /**
     * Generated from protobuf field <code>string shipping_method = 18;</code>
     */
    private $shipping_method = '';
    /**
     * Generated from protobuf field <code>int32 goods_type = 19;</code>
     */
    private $goods_type = 0;
    /**
     * Generated from protobuf field <code>int32 last_modified = 20;</code>
     */
    private $last_modified = 0;
    /**
     * Generated from protobuf field <code>int32 save_one_month = 21;</code>
     */
    private $save_one_month = 0;
    /**
     * Generated from protobuf field <code>int32 is_selected = 22;</code>
     */
    private $is_selected = 0;
    /**
     * Generated from protobuf field <code>int32 wj_linkid = 23;</code>
     */
    private $wj_linkid = 0;
    /**
     * Generated from protobuf field <code>int32 wj_linkid_source = 24;</code>
     */
    private $wj_linkid_source = 0;
    /**
     * Generated from protobuf field <code>int32 gift = 25;</code>
     */
    private $gift = 0;
    /**
     * Generated from protobuf field <code>string zaful_source = 26;</code>
     */
    private $zaful_source = '';
    /**
     * Generated from protobuf field <code>int32 buytype = 27;</code>
     */
    private $buytype = 0;
    /**
     * Generated from protobuf field <code>string lang = 28;</code>
     */
    private $lang = '';
    /**
     * Generated from protobuf field <code>int32 discountPriceType = 29;</code>
     */
    private $discountPriceType = 0;
    /**
     * Generated from protobuf field <code>string app_device_id = 30;</code>
     */
    private $app_device_id = '';
    /**
     * Generated from protobuf field <code>int32 pipeline_id = 31;</code>
     */
    private $pipeline_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $rec_id
     *     @type int $user_id
     *     @type string $session_id
     *     @type int $goods_id
     *     @type string $goods_sn
     *     @type string $goods_name
     *     @type float $market_price
     *     @type float $goods_price
     *     @type int $goods_number
     *     @type string $goods_attr
     *     @type string $custom_size
     *     @type int $can_handsel
     *     @type string $goods_attr_id
     *     @type int $goods_off
     *     @type int $lmt_num
     *     @type int $addtime
     *     @type string $attr_goods_sn
     *     @type string $shipping_method
     *     @type int $goods_type
     *     @type int $last_modified
     *     @type int $save_one_month
     *     @type int $is_selected
     *     @type int $wj_linkid
     *     @type int $wj_linkid_source
     *     @type int $gift
     *     @type string $zaful_source
     *     @type int $buytype
     *     @type string $lang
     *     @type int $discountPriceType
     *     @type string $app_device_id
     *     @type int $pipeline_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cart::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 rec_id = 1;</code>
     * @return int
     */
    public function getRecId()
    {
        return $this->rec_id;
    }

    /**
     * Generated from protobuf field <code>int32 rec_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRecId($var)
    {
        GPBUtil::checkInt32($var);
        $this->rec_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session_id = 3;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>string session_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 goods_id = 4;</code>
     * @return int
     */
    public function getGoodsId()
    {
        return $this->goods_id;
    }

    /**
     * Generated from protobuf field <code>int32 goods_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setGoodsId($var)
    {
        GPBUtil::checkInt32($var);
        $this->goods_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string goods_sn = 5;</code>
     * @return string
     */
    public function getGoodsSn()
    {
        return $this->goods_sn;
    }

    /**
     * Generated from protobuf field <code>string goods_sn = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGoodsSn($var)
    {
        GPBUtil::checkString($var, True);
        $this->goods_sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string goods_name = 6;</code>
     * @return string
     */
    public function getGoodsName()
    {
        return $this->goods_name;
    }

    /**
     * Generated from protobuf field <code>string goods_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setGoodsName($var)
    {
        GPBUtil::checkString($var, True);
        $this->goods_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double market_price = 7;</code>
     * @return float
     */
    public function getMarketPrice()
    {
        return $this->market_price;
    }

    /**
     * Generated from protobuf field <code>double market_price = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setMarketPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->market_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double goods_price = 8;</code>
     * @return float
     */
    public function getGoodsPrice()
    {
        return $this->goods_price;
    }

    /**
     * Generated from protobuf field <code>double goods_price = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setGoodsPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->goods_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 goods_number = 9;</code>
     * @return int
     */
    public function getGoodsNumber()
    {
        return $this->goods_number;
    }

    /**
     * Generated from protobuf field <code>int32 goods_number = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setGoodsNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->goods_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string goods_attr = 10;</code>
     * @return string
     */
    public function getGoodsAttr()
    {
        return $this->goods_attr;
    }

    /**
     * Generated from protobuf field <code>string goods_attr = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setGoodsAttr($var)
    {
        GPBUtil::checkString($var, True);
        $this->goods_attr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string custom_size = 11;</code>
     * @return string
     */
    public function getCustomSize()
    {
        return $this->custom_size;
    }

    /**
     * Generated from protobuf field <code>string custom_size = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomSize($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 can_handsel = 12;</code>
     * @return int
     */
    public function getCanHandsel()
    {
        return $this->can_handsel;
    }

    /**
     * Generated from protobuf field <code>int32 can_handsel = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setCanHandsel($var)
    {
        GPBUtil::checkInt32($var);
        $this->can_handsel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string goods_attr_id = 13;</code>
     * @return string
     */
    public function getGoodsAttrId()
    {
        return $this->goods_attr_id;
    }

    /**
     * Generated from protobuf field <code>string goods_attr_id = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setGoodsAttrId($var)
    {
        GPBUtil::checkString($var, True);
        $this->goods_attr_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 goods_off = 14;</code>
     * @return int
     */
    public function getGoodsOff()
    {
        return $this->goods_off;
    }

    /**
     * Generated from protobuf field <code>int32 goods_off = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setGoodsOff($var)
    {
        GPBUtil::checkInt32($var);
        $this->goods_off = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 lmt_num = 15;</code>
     * @return int
     */
    public function getLmtNum()
    {
        return $this->lmt_num;
    }

    /**
     * Generated from protobuf field <code>int32 lmt_num = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setLmtNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->lmt_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 addtime = 16;</code>
     * @return int
     */
    public function getAddtime()
    {
        return $this->addtime;
    }

    /**
     * Generated from protobuf field <code>int32 addtime = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setAddtime($var)
    {
        GPBUtil::checkInt32($var);
        $this->addtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attr_goods_sn = 17;</code>
     * @return string
     */
    public function getAttrGoodsSn()
    {
        return $this->attr_goods_sn;
    }

    /**
     * Generated from protobuf field <code>string attr_goods_sn = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setAttrGoodsSn($var)
    {
        GPBUtil::checkString($var, True);
        $this->attr_goods_sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shipping_method = 18;</code>
     * @return string
     */
    public function getShippingMethod()
    {
        return $this->shipping_method;
    }

    /**
     * Generated from protobuf field <code>string shipping_method = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->shipping_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 goods_type = 19;</code>
     * @return int
     */
    public function getGoodsType()
    {
        return $this->goods_type;
    }

    /**
     * Generated from protobuf field <code>int32 goods_type = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setGoodsType($var)
    {
        GPBUtil::checkInt32($var);
        $this->goods_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 last_modified = 20;</code>
     * @return int
     */
    public function getLastModified()
    {
        return $this->last_modified;
    }

    /**
     * Generated from protobuf field <code>int32 last_modified = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setLastModified($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_modified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 save_one_month = 21;</code>
     * @return int
     */
    public function getSaveOneMonth()
    {
        return $this->save_one_month;
    }

    /**
     * Generated from protobuf field <code>int32 save_one_month = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setSaveOneMonth($var)
    {
        GPBUtil::checkInt32($var);
        $this->save_one_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 is_selected = 22;</code>
     * @return int
     */
    public function getIsSelected()
    {
        return $this->is_selected;
    }

    /**
     * Generated from protobuf field <code>int32 is_selected = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setIsSelected($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_selected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 wj_linkid = 23;</code>
     * @return int
     */
    public function getWjLinkid()
    {
        return $this->wj_linkid;
    }

    /**
     * Generated from protobuf field <code>int32 wj_linkid = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setWjLinkid($var)
    {
        GPBUtil::checkInt32($var);
        $this->wj_linkid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 wj_linkid_source = 24;</code>
     * @return int
     */
    public function getWjLinkidSource()
    {
        return $this->wj_linkid_source;
    }

    /**
     * Generated from protobuf field <code>int32 wj_linkid_source = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setWjLinkidSource($var)
    {
        GPBUtil::checkInt32($var);
        $this->wj_linkid_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 gift = 25;</code>
     * @return int
     */
    public function getGift()
    {
        return $this->gift;
    }

    /**
     * Generated from protobuf field <code>int32 gift = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setGift($var)
    {
        GPBUtil::checkInt32($var);
        $this->gift = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string zaful_source = 26;</code>
     * @return string
     */
    public function getZafulSource()
    {
        return $this->zaful_source;
    }

    /**
     * Generated from protobuf field <code>string zaful_source = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setZafulSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->zaful_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 buytype = 27;</code>
     * @return int
     */
    public function getBuytype()
    {
        return $this->buytype;
    }

    /**
     * Generated from protobuf field <code>int32 buytype = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setBuytype($var)
    {
        GPBUtil::checkInt32($var);
        $this->buytype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lang = 28;</code>
     * @return string
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * Generated from protobuf field <code>string lang = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 discountPriceType = 29;</code>
     * @return int
     */
    public function getDiscountPriceType()
    {
        return $this->discountPriceType;
    }

    /**
     * Generated from protobuf field <code>int32 discountPriceType = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setDiscountPriceType($var)
    {
        GPBUtil::checkInt32($var);
        $this->discountPriceType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_device_id = 30;</code>
     * @return string
     */
    public function getAppDeviceId()
    {
        return $this->app_device_id;
    }

    /**
     * Generated from protobuf field <code>string app_device_id = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setAppDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pipeline_id = 31;</code>
     * @return int
     */
    public function getPipelineId()
    {
        return $this->pipeline_id;
    }

    /**
     * Generated from protobuf field <code>int32 pipeline_id = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setPipelineId($var)
    {
        GPBUtil::checkInt32($var);
        $this->pipeline_id = $var;

        return $this;
    }

}

