<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto

namespace Cart;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>cart.CartResponse</code>
 */
class CartResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool code = 1;</code>
     */
    private $code = false;
    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    private $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $code
     *     @type string $msg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cart::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool code = 1;</code>
     * @return bool
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>bool code = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkBool($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

